### PR TITLE
:source-dirs -> :source-paths in project.clj

### PR DESCRIPTION
**Pull request by nickik**
I could not run (arachne/config ...) with :source-dirs. Its already :source-paths in the arachne-docs project code.

### CODE REVIEW

**Comment by iku000888** [comment]
:+1:

**Comment by iku000888** [comment]
FWIW, reference that it should be :source-paths
https://github.com/technomancy/leiningen/blob/master/sample.project.clj

This is a rather frustrating documentation error, so I do hope this PR gets merged soon...

**Comment by iku000888** [comment]
@nickik Might be worth your time to update the title?
Perhaps ":source-dirs -> :source-paths in project.clj" or something that tells what issue this PR addresses.

**Comment by nickik** [comment]
@iku000888 Thanks for pushing this. I did not remember, I hope it will get in soon.

**Comment by nickik** [comment]
Wrong button :)

**Comment by webappzero** [comment]
@nickik Thank you for posting this important tutorial fix. We've had some issues with GH notifications in the past and I'm assuming that explains the delay. Luke is preparing for the Conj, but I've raised this issue to his attention.

**Comment by levand** [comment]
Thanks! So sorry about the delay getting it in. This is important :)

**Comment by iku000888** [comment]
Thanks @webappzero @levand !

**Pull request merged**
